[theme]

# Primary accent color for interactive elements.
primaryColor = "#fd8d3c"

# Background color for the main content area.
backgroundColor = "#262730"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#0E1117"

# Color used for almost all text.
textColor = "#FAFAFA"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"